### ISSUE TITLE
Sample.py breaks on second run

### ISSUE THREAD

**Issue by candeira** [pybee/batavia#2]
When running the testserver and running sample.py via its button, it works fine the first time, but throws an exception on second and subsequent button pushes:

Caught exception during execution: TypeError: Cannot read property 'hasOwnProperty' of undefinedCaught exception during execution: TypeError: this.manage_block_stack is not a functionCaught exception during execution: null

This was on Chrome 44.0.2403.125 (64-bit) on Ubuntu 14.04.

![image](https://cloud.githubusercontent.com/assets/91694/9216150/f83f91d0-40f7-11e5-91dc-764f0b3bf6a6.png)

**Comment by freakboy3742** [comment]
I've done some investigation; the problem appears to be leakage between VM instances. Each time you press the "Run" button, it creates a fresh VM. However, on the second execution, references to the first VM are still hanging around; the crash is caused because the code is running in the first VM, but asking the second VM for stack information (that doesn't exist, because nothing has been executed there).

The obvious "make it go away" fix is to instantiate a single global VM for the page. However, clearly there's an underlying issue with the wrong VM being stored in a closure somewhere. I either need to turn the VM into a Borg, or find where the closure leakage is happening.
