### ISSUE TITLE
property support

### ISSUE THREAD

**Issue by shaib** [pybee/batavia#381]
Hi,

Current Batavia says, if you try to define a property:
```
17:25:57.800 Traceback (most recent call last):
  File "/home/shai/beeware/toga/src/django/toga_django/bootstrap.py", line 3, in bootstrap
  File "/home/shai/beeware/toga/src/django/toga_django/impl/__init__.py", line 33, in <module>
  File "/home/shai/beeware/toga/src/django/toga_django/impl/__init__.py", line 57, in Button
NotImplementedError: Builtin Batavia function 'property' not implemented1 batavia.js:19229:1
```
As you might guess from this traceback, I'm working on the Web (Django) backend, and properties are required if you want to make controls which change in response to events.

This issue may, or may not, be considered a sub-task of #47.

**Comment by shaib** [comment]
So, I started looking into implementing this, and it is not a simple function to write. We need to add support in the core.

The current `byte_LOAD_ATTR()` function probably needs to support it, but unless I'm missing something, it does not -- but further, it lets `__getattr__` override existing attributes and doesn't do `__getattribute__` at all. Looks like a bug.

**Comment by freakboy3742** [comment]
The `__getattr__` problem you've mentioned is almost certainly a bug. First pass at `byte_LOAD_ATTR` was "get it working"; fully compliant `__getattribute__`/`__getattr__` chaining was further down the list.

I can say from my experience with Java and VOC that `property` turns out to be not that hard to implement - *once* you've got the `__getattr__` stuff sorted out.

**Comment by freakboy3742** [comment]
property has now been implemented.
