### ISSUE TITLE
cleanse_javascript doesn't always know how to handle input

### ISSUE THREAD

**Issue by jstoebel** [pybee/batavia#405]
the function `cleanse_javascript` in `test/utils.py` performs several transformations on output javascript during tests. Some of them are:

- dropping the additional zeros from a decimal (`3.000` -> `3.0`)
- Normalize true and false to True and False (`true` -> `True`)
- Replace large integers in a complex number with floating point.

The issue arises when we try to print strings like `'3.000'` or `'true'`. `cleanse_javascript` performs the transformation when it shouldn't.

One idea here might be to relieve this function of the responsibility of transforming output since it has no way of knowing what specifically produced it. Instead, the responsibility for properly representing, for example `3.000` is handled elsewhere. I'd be happy to work on this, but since it seems like it could touch a lot, I would love feedback on the best approach before getting started.

**Comment by freakboy3742** [comment]
Agreed that what you describe is a problem. Universally applying the full set of transformations is potentially risky, for the reasons you've described.

There is a *partial* solution already in place - it's possible to define the list of transformations that will be used on a per-test class basis. However, the list of "base" transforms (like the ones you've pointed out) is constant. 

On suggestion: name all the transforms, and then allow each test to turn the transform on or off on a per-test or per-TestCase basis (using class variables or attributes on a decorator). That on/off configuration then gets passed to the cleanse method. Example usage:
```
class MyTest(TranspileTestCase):
    fix_boolean_repr = True
    fix_trailing_zeros = False

    @transforms(
        fix_trailing_zeros = True
    )
    def test_something(self):
        # trailing zeros and booleans modified.
        ...

    def test_otherthing(self):
        # trailing zeros not modified, booleans are
        ...
```

Does that make sense?

**Comment by jstoebel** [comment]
this sounds good. I'll give this a shot.

**Comment by jstoebel** [comment]
I'm a little confused on how to use decorators in this way. If I'm understanding this correctly, I would need a decorator that when applied, modifies `self.fix_boolean_repr` and `self.fix_trailing_zeros` How is that done? Or am I approaching this wrong?

**Comment by freakboy3742** [comment]
The decorator doesn't *have* to modify `self.fix_boolean_repr`et al; it just needs to modify the value that is used as part of the conversion process. You *could* do this by saving the global value, setting the local value, running the test, and then restoring the global value; but it could get fiddly to ensure that the changes you make are always unrolled in the case of errors.

Your suggested approach about adding arguments with defaults would also work - except that the list of arguments is going to get very long. There's already half a dozen conversions that could be made; I can only imagine this list will grow with time. 

One solution would be to use a `**kwargs` argument - that would allow for arbitrary expansion of the flags that you could use. However, unless you also add a lot of internal error checking, you could easily end up with flags that are ignored due to typos.

I'd suggest a better way would be to wrap the "cleaning" process up into a class that has state. Each test would instantiate an instance of the "cleaner" class. The construction of the cleaner would take arguments from the test class. You avoid the error handling problem because the cleaner class constructor itself has explicit arguments.

The decorator then gives you a clean way to express  in code what has been turned on and off; internally, the decorator modifies the flags on the cleaner class. This means you only have to have a single keyword argument - the cleaner - and internally, the cleaner can be expanded as needed as time goes on.

Does that make sense?

**Comment by jstoebel** [comment]
great, so is this is the general idea?

```
class JSCleanse:

    def __init__(self, shorten_float=True, fix_bool=True, fix_complex=True):
        self.shorten_float = shorten_float
        self.fix_bool = fix_bool
        self.fix_complex = fix_complex

    def cleanse(self, input, substitutions):
        """
        perform cleanse of javascript based on specifications
        """
        # `cleanse_javascript` implementation moved here
```

And then in a test case:

```
class MyTest(TranspileTestCase):

...
    def test_some_things(self):
        # set up a test string

        cleanse_obj = JSCleanse(fix_bool = False)
        self.assertCodeExecution(tests, cleanse_obj)

```
And finally `assertCodeExecution` is modified to use `cleanse_obj` to perform the JS cleanse

Is that the general idea or am I missing something?

**Comment by jstoebel** [comment]
The part I am confused about is how a decorator figures into all of this. Could you show me an example of how this would be used?

**Comment by jstoebel** [comment]
closed by [pr391](https://github.com/pybee/batavia/pull/391)
