### ISSUE TITLE
Contributing to Batavia Doc Enhancement

### ISSUE THREAD

**Issue by utkarsh-raj** [pybee/batavia#766]
## Expected Behavior

The current documentation for Batavia Installation tells one to use pip instead of pip3, but the Python version supported is >= 3. Also, in the instruction to run the tests in text mode (setup.py) runs python instead of python3. 

## Current Behavior

If the user does not activate the venv, python can throw errors if both Python 2 and Python 3 are installed in the system.
Even if the user has venv, it is a safer practice to explicitly state the version of Python being run.

**Comment by freakboy3742** [comment]
As noted on the PR, this isn't necessary. If you're in the virtual environment, `python` will point at the version created by the virtual environment. I'd argue it's safer to *not* use the prefix - because by using `python`, you're guaranteeing that you're in an activated virtual environment. If you're not, `python` will start a Python2 interpreter, and you'll get an error.
